server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://1.117.48.220:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect
    username: root
    password: toor
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

eureka:
  client:
    register-with-eureka: true #是否将自己注入进eureka-server中 默认为true
    #是否从eurekaServer中抓取已经注册的信息。单节点无所谓，集群必须设置为true,才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-payment-service8001
    prefer-ip-address: true   #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 30 # eureka客户端向服务端发送心跳的时间
    lease-expiration-duration-in-seconds: 90 # Eureka服务端在收到最后一次后等待时间上限，单位为秒

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.athome.springcloud.entities

