server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment8004
  datasource:
    url: jdbc:mysql://1.117.48.220:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect
    username: root
    password: toor
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

  cloud:
    zookeeper:
      connect-string: 1.117.48.220:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.athome.springcloud.entities
